steps:
  - name: ':docker: :package:'
    plugins:
      'docker-compose#v1.7.0':
        build: fusion-plugin-react-redux
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
    agents:
      queue: builders
  - name: ':docker: :package: node8'
    plugins:
      'docker-compose#v1.7.0':
        build: fusion-plugin-react-redux-node-last
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
    agents:
      queue: builders
  - wait
  - command: yarn flow
    name: ':flowtype:'
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-plugin-react-redux
    agents:
      queue: workers
  - command: yarn flow
    name: ':flowtype: node8'
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-plugin-react-redux-node-last
    agents:
      queue: workers
  - name: ':eslint:'
    command: yarn lint
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-plugin-react-redux
    agents:
      queue: workers
  - name: ':eslint: node8'
    command: yarn lint
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-plugin-react-redux-node-last
    agents:
      queue: workers
  - name: ':chrome: :white_check_mark:'
    command: .buildkite/browserTests
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-plugin-react-redux
    agents:
      queue: workers
  - name: ':chrome: :white_check_mark: node8'
    command: .buildkite/browserTests
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-plugin-react-redux-node-last
    agents:
      queue: workers
  - name: ':node: :white_check_mark:'
    command: .buildkite/nodeTests
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-plugin-react-redux
    agents:
      queue: workers
  - name: ':node: :white_check_mark: node8'
    command: .buildkite/nodeTests
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-plugin-react-redux-node-last
    agents:
      queue: workers
